Repository kdozlo/solsolpokect, pull requests merged in 2023-09, with the labels that each got.

#9 Feat : #8 다이어리 패키지 레포에서 JPA 상속
  server/src/main/java/team21/solsolpokect/diary/repository/DiaryRepository.java
  server/src/main/java/team21/solsolpokect/diary/repository/FeedbackRepository.java
  server/src/main/java/team21/solsolpokect/diary/repository/MonthlyGoalMoneyRepository.java
Labels: enhancement

#12 Feat : #10 Mission 패키지 JPA 상속
  server/src/main/java/team21/solsolpokect/mission/repository/MissionRepository.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
Labels: enhancement, fix

#17 Feat : #16 Mission 패키지 DTO 작성
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionAllowRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionCreateRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionPictureRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/response/MissionInfoDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/response/MissionInfosResponseDto.java
Labels: enhancement

#20 Feat : #19 신한은행 OpenAPI 불러오기
  server/build.gradle
  server/src/main/java/team21/solsolpokect/common/infra/RestTemplateConfig.java
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiController.java
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiService.java
Labels: enhancement

#22 Feat : security 초안 작성
  server/src/main/java/team21/solsolpokect/common/config/WebSecurityConfig.java
  server/src/main/java/team21/solsolpokect/common/security/CustomAuthenticationEntryPoint.java
Labels: enhancement

#24 Feat : 가족 구성원 가계부 상세 조회 API 작성
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/diary/controller/DiaryController.java
  server/src/main/java/team21/solsolpokect/diary/dto/response/diary/DiaryInfoDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
Labels: enhancement

#27 Feat : #18 Transfer 패키지 DTO 작성
  server/src/main/java/team21/solsolpokect/transfer/dto/request/AutoTransferCreateRequestDto.java
  server/src/main/java/team21/solsolpokect/transfer/dto/request/AutoTransferModifyRequestDto.java
  server/src/main/java/team21/solsolpokect/transfer/dto/response/AutoTransferResponseDto.java
Labels: enhancement

#30 Feat : #29 mission controller 기능 개발
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/mission/controller/MissionController.java
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionCompleteRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/entity/Mission.java
Labels: enhancement

#37 Feat/#31 mission service 구현
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/mission/controller/MissionController.java
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionCompleteRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/response/MissionInfoDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/response/MissionInfosResponseDto.java
  server/src/main/java/team21/solsolpokect/mission/entity/Mission.java
  server/src/main/java/team21/solsolpokect/mission/repository/MissionRepository.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
  server/src/main/java/team21/solsolpokect/transfer/entity/AutoTransfer.java
  server/src/main/java/team21/solsolpokect/user/entity/Users.java
  server/src/main/java/team21/solsolpokect/user/repository/UsersRepository.java
Labels: enhancement

#40 Feat : #32 feedback 컴포넌트 개발
  client/.eslintrc.json
  client/.prettierrc.json
  client/components/AccountBookFeedback.jsx
  client/components/AccountBookProfile.jsx
  client/components/AccountBookUserInfo.jsx
  client/components/Feedback/FeedbackComment.jsx
  client/components/Feedback/FeedbackWriteComment.jsx
  client/components/Feedback/ScoreDropdown.jsx
  client/package-lock.json
  client/package.json
  client/pages/AccountBook.jsx
  client/recoil/accountBook.js
Labels: enhancement

#42 Feat/#39 auto transfer controller 기능 개발
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/transfer/controller/AutoTransferController.java
Labels: enhancement

#45 Feat : feedback 완료
  server/src/main/java/team21/solsolpokect/common/entity/BaseTime.java
  server/src/main/java/team21/solsolpokect/common/entity/DateUtils.java
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/diary/controller/FeedbackController.java
  server/src/main/java/team21/solsolpokect/diary/dto/request/feedback/FeedbackRequestDto.java
  server/src/main/java/team21/solsolpokect/diary/dto/response/feedback/FeedbackInfosResponseDto.java
  server/src/main/java/team21/solsolpokect/diary/entity/Feedback.java
  server/src/main/java/team21/solsolpokect/diary/repository/DiaryRepository.java
  server/src/main/java/team21/solsolpokect/diary/repository/FeedbackRepository.java
  server/src/main/java/team21/solsolpokect/diary/repository/MonthlyGoalMoneyRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/FeedbackService.java
  server/src/main/java/team21/solsolpokect/transfer/controller/AutoTransferController.java
Labels: enhancement

#46 Feat/#43 auto transfer service
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/diary/entity/Feedback.java
  server/src/main/java/team21/solsolpokect/mission/repository/MissionRepository.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
  server/src/main/java/team21/solsolpokect/transfer/controller/AutoTransferController.java
  server/src/main/java/team21/solsolpokect/transfer/dto/request/AutoTransferCreateRequestDto.java
  server/src/main/java/team21/solsolpokect/transfer/dto/request/AutoTransferUpdateRequestDto.java
  server/src/main/java/team21/solsolpokect/transfer/dto/response/AutoTransferResponseDto.java
  server/src/main/java/team21/solsolpokect/transfer/entity/AutoTransfer.java
  server/src/main/java/team21/solsolpokect/transfer/repository/AutoTransferRepository.java
  server/src/main/java/team21/solsolpokect/transfer/service/AutoTransferService.java
Labels: enhancement

#49 Feat/#48 family controller 기능 개발
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/family/controller/FamilyController.java
  server/src/main/java/team21/solsolpokect/family/dto/request/FamilyCreateRequestDto.java
  server/src/main/java/team21/solsolpokect/family/dto/response/FamilyInfoResponseDto.java
  server/src/main/java/team21/solsolpokect/family/entity/Family.java
Labels: enhancement

#52 Feat/#50 family service 구현
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/family/controller/FamilyController.java
  server/src/main/java/team21/solsolpokect/family/dto/request/FamilyCreateRequestDto.java
  server/src/main/java/team21/solsolpokect/family/dto/response/FamilyDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/family/dto/response/FamilyInfoResponseDto.java
  server/src/main/java/team21/solsolpokect/family/entity/Family.java
  server/src/main/java/team21/solsolpokect/family/repository/FamilyRepository.java
  server/src/main/java/team21/solsolpokect/family/service/FamilyService.java
  server/src/main/java/team21/solsolpokect/user/entity/Users.java
  server/src/main/java/team21/solsolpokect/user/repository/UsersRepository.java
Labels: enhancement

#60 Feat : users 구현 및 JWT 토큰 추가
  server/build.gradle
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/common/jwt/JwtAuthFilter.java
  server/src/main/java/team21/solsolpokect/common/jwt/JwtUtil.java
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/common/security/UserDetailsImpl.java
  server/src/main/java/team21/solsolpokect/common/security/UserDetailsServiceImpl.java
  server/src/main/java/team21/solsolpokect/diary/repository/FeedbackRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
  server/src/main/java/team21/solsolpokect/diary/service/FeedbackService.java
  server/src/main/java/team21/solsolpokect/diary/service/MonthlyGoalMoneyService.java
  server/src/main/java/team21/solsolpokect/family/service/FamilyService.java
  server/src/main/java/team21/solsolpokect/user/controller/UsersController.java
  server/src/main/java/team21/solsolpokect/user/dto/request/LoginRequestDto.java
  server/src/main/java/team21/solsolpokect/user/dto/request/SignupRequestDto.java
  server/src/main/java/team21/solsolpokect/user/entity/Users.java
  server/src/main/java/team21/solsolpokect/user/repository/UsersRepository.java
  server/src/main/java/team21/solsolpokect/user/service/UsersService.java
Labels: documentation, enhancement, fix

#58 Feat/#57 mission img upload
  server/build.gradle
  server/src/main/java/team21/solsolpokect/common/config/AmazonS3Config.java
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/common/service/S3Uploader.java
  server/src/main/java/team21/solsolpokect/family/controller/FamilyController.java
  server/src/main/java/team21/solsolpokect/mission/controller/MissionController.java
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionPictureRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/entity/Mission.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
  server/src/main/java/team21/solsolpokect/transfer/entity/AutoTransfer.java
Labels: enhancement

#56 Fix: 거래 이체 내역 화면에서 State 갱신 안되는 문제 해결
  client/pages/TransactionHistory.jsx
  client/services/apis/accountListAPI.js
Labels: enhancement

#66 Feat : UserInfo API 구현
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiService.java
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/user/controller/UsersController.java
  server/src/main/java/team21/solsolpokect/user/dto/response/UsersInfoResponseDto.java
  server/src/main/java/team21/solsolpokect/user/service/UsersService.java
Labels: enhancement

#68 Feat/#63 call shinhan transfer 구현
  server/src/main/java/team21/solsolpokect/SolsolpokectApplication.java
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiController.java
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiService.java
  server/src/main/java/team21/solsolpokect/family/dto/response/FamilyDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/family/repository/FamilyRepository.java
  server/src/main/java/team21/solsolpokect/mission/repository/MissionRepository.java
  server/src/main/java/team21/solsolpokect/transfer/controller/AutoTransferController.java
  server/src/main/java/team21/solsolpokect/transfer/entity/AutoTransfer.java
  server/src/main/java/team21/solsolpokect/transfer/repository/AutoTransferRepository.java
  server/src/main/java/team21/solsolpokect/transfer/service/AutoTransferService.java
Labels: enhancement, fix

#69 Feat : 일일 점수 작성 및 수정 API 구현
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/diary/controller/DiaryController.java
  server/src/main/java/team21/solsolpokect/diary/dto/request/diary/DiaryScoreRequestDto.java
  server/src/main/java/team21/solsolpokect/diary/entity/Diary.java
  server/src/main/java/team21/solsolpokect/diary/repository/DiaryRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
Labels: enhancement

#72 Fix : Feedback 예외처리 추가 및 수정
  server/src/main/java/team21/solsolpokect/common/entity/DateUtils.java
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/diary/entity/Diary.java
  server/src/main/java/team21/solsolpokect/diary/repository/DiaryRepository.java
  server/src/main/java/team21/solsolpokect/diary/repository/FeedbackRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
  server/src/main/java/team21/solsolpokect/diary/service/FeedbackService.java
Labels: fix

#73 Fix : FamilyService, FamilyDetailResponseDto 수정
  server/src/main/java/team21/solsolpokect/family/dto/response/FamilyDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/family/service/FamilyService.java
Labels: fix

#76 Fix : 다이어리 및 로그인 수정
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/diary/dto/request/monthlygoal/MonthlyGoalMoneyRequestDto.java
  server/src/main/java/team21/solsolpokect/diary/entity/MonthlyGoalMoney.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
  server/src/main/java/team21/solsolpokect/diary/service/MonthlyGoalMoneyService.java
  server/src/main/java/team21/solsolpokect/user/controller/UsersController.java
  server/src/main/java/team21/solsolpokect/user/service/UsersService.java
Labels: enhancement, fix

#77 Refactor : 클래스 첫 줄 띄우기, 쓸모없는 import 삭제
  server/src/main/java/team21/solsolpokect/common/entity/DateUtils.java
  server/src/main/java/team21/solsolpokect/common/exception/CustomException.java
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/diary/entity/Feedback.java
  server/src/main/java/team21/solsolpokect/diary/repository/MonthlyGoalMoneyRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
  server/src/main/java/team21/solsolpokect/user/service/UsersService.java
Labels: fix

#78 Feat/#75 mission complete reward
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiService.java
  server/src/main/java/team21/solsolpokect/family/dto/response/FamilyDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/family/service/FamilyService.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
  server/src/main/java/team21/solsolpokect/transfer/service/AutoTransferService.java
  server/src/main/java/team21/solsolpokect/user/entity/Users.java
Labels: enhancement

#80 Feat : 도전 과제 생성 시 허용 여부 판단 기능 구현
  server/src/main/java/team21/solsolpokect/mission/controller/MissionController.java
  server/src/main/java/team21/solsolpokect/mission/entity/Mission.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
Labels: enhancement

#84 Fix : callShinhanApi -> callShinhanTransactionApi
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiController.java
  server/src/main/java/team21/solsolpokect/common/infra/ShinhanApiService.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
Labels: fix

#88 Fix/#85 score create
  server/src/main/java/team21/solsolpokect/diary/dto/request/diary/DiaryScoreRequestDto.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
  server/src/main/java/team21/solsolpokect/user/service/UsersService.java
Labels: fix

#91 Feat/#90 credit score update
  server/src/main/java/team21/solsolpokect/diary/entity/Diary.java
  server/src/main/java/team21/solsolpokect/diary/service/DiaryService.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
  server/src/main/java/team21/solsolpokect/user/entity/Users.java
Labels: bug, enhancement

#97 Feat: 용돈 관리 화면 개발
  client/App.js
  client/assets/icons/check.png
  client/assets/icons/more.png
  client/assets/icons/plus.png
  client/assets/images/bankLogo/giup.png
  client/assets/images/bankLogo/gukmin.png
  client/assets/images/bankLogo/nonghyup.png
  client/components/AccountInfo.jsx
  client/components/AddTodoInput.jsx
  client/components/Calendar/ArrowButton.jsx
  client/components/Calendar/CalendarBody.jsx
  client/components/Calendar/CalendarHeader.jsx
  client/components/Calendar/CalendarItem.jsx
  client/components/Family/AccountBookMember.jsx
  client/components/Family/FamilyList.jsx
  client/components/Family/PocketMoneyMember.jsx
  client/components/FamilyList.jsx
  client/components/GoBackHeader.jsx
  client/components/NumberPad.jsx
  client/components/PocketMoney/AutomaticPaymentList.jsx
  client/components/PocketMoney/HamburgerModal.jsx
  client/components/PocketMoney/PocketMoneyModal.jsx
  client/components/PocketMoney/PocketMoneyReqest.jsx
  client/components/Transaction/TransactionFilter.jsx
  client/components/Transaction/TransactionItem.jsx
  client/components/Transaction/TransactionList.jsx
  client/components/Transaction/TransactionTypeModal.jsx
  client/components/Transfer/AccountBalance.jsx
  client/components/Transfer/BankListModal.jsx
  client/components/Transfer/NumberPad.jsx
  client/components/Transfer/PasswordModal.jsx
  client/components/Transfer/PasswordPins.jsx
  client/components/Transfer/TransferMoney.jsx
  client/constants/icons.js
  client/constants/images.js
  client/constants/theme.js
  client/hooks/use-calendar.jsx
  client/package-lock.json
  client/package.json
  client/pages/AccountBook.jsx
  client/pages/CheckTransferInfo.jsx
  client/pages/ManagingPocketMoney.jsx
  client/pages/SelectAccount.jsx
  client/pages/SelectMoney.jsx
  client/pages/SignUp.jsx
  client/pages/TransactionHistory.jsx
  client/pages/TransferSuccess.jsx
  client/recoil/accountBook.js
  client/recoil/auth.js
  client/recoil/pocketMoney.js
  client/recoil/transaction.js
  client/recoil/transfer.js
  client/test/dummyData/managingPocketMoney.js
  client/test/dummyData/user.js
  client/utils/TransferUtils.js
  client/utils/const/auth.js
  client/utils/const/bank.js
Labels: enhancement

#98 Fix/#93 feedback
  server/src/main/java/team21/solsolpokect/diary/dto/request/feedback/FeedbackRequestDto.java
  server/src/main/java/team21/solsolpokect/diary/repository/DiaryRepository.java
  server/src/main/java/team21/solsolpokect/diary/repository/FeedbackRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/FeedbackService.java
Labels: enhancement, fix

#102 Fix/#101 mission list
  server/src/main/java/team21/solsolpokect/mission/repository/MissionRepository.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
  server/src/main/java/team21/solsolpokect/transfer/entity/AutoTransfer.java
Labels: enhancement, fix

#103 Feat : redis concurrency control
  server/build.gradle
  server/src/main/java/team21/solsolpokect/common/handler/TransactionHandler.java
  server/src/main/java/team21/solsolpokect/common/redis/RedisConfig.java
  server/src/main/java/team21/solsolpokect/common/redis/RedisLockRepository.java
  server/src/main/java/team21/solsolpokect/user/service/UsersService.java
Labels: documentation, enhancement

#107 Feat : redis distribution lock 구현
  server/build.gradle
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/common/redis/RedisLockRepository.java
Labels: enhancement

#109 Feat/#104 goal money detail
  server/src/main/java/team21/solsolpokect/common/entity/DateUtils.java
  server/src/main/java/team21/solsolpokect/common/exception/ErrorType.java
  server/src/main/java/team21/solsolpokect/common/response/MsgType.java
  server/src/main/java/team21/solsolpokect/diary/controller/MonthlyGoalMoneyController.java
  server/src/main/java/team21/solsolpokect/diary/dto/response/MonthlyGoalMoneyResponseDto/MonthlyGoalMoneyResponseDto.java
  server/src/main/java/team21/solsolpokect/diary/entity/MonthlyGoalMoney.java
  server/src/main/java/team21/solsolpokect/diary/repository/MonthlyGoalMoneyRepository.java
  server/src/main/java/team21/solsolpokect/diary/service/MonthlyGoalMoneyService.java
Labels: enhancement

#110 Fix : 미션 변경
  server/src/main/java/team21/solsolpokect/mission/controller/MissionController.java
  server/src/main/java/team21/solsolpokect/mission/dto/request/MissionCreateRequestDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/response/MissionInfoDetailResponseDto.java
  server/src/main/java/team21/solsolpokect/mission/dto/response/MissionInfosResponseDto.java
  server/src/main/java/team21/solsolpokect/mission/entity/Mission.java
  server/src/main/java/team21/solsolpokect/mission/service/MissionService.java
Labels: fix

#114 Feat: 발표용 결과물 merge
  client/App.js
  client/components/AccountBookFeedback.jsx
  client/components/AccountBookProfile.jsx
  client/components/AccountBookUserInfo.jsx
  client/components/Family/AccountBookMember.jsx
  client/components/Family/FamilyList.jsx
  client/components/Family/PocketMoneyMember.jsx
  client/components/Feedback/FeedbackComment.jsx
  client/components/Feedback/FeedbackWriteComment.jsx
  client/components/Feedback/ScoreDropdown.jsx
  client/components/GoBackHeader.jsx
  client/components/PocketMoney/AutomaticPaymentList.jsx
  client/components/PocketMoney/DateDropdown.jsx
  client/components/PocketMoney/HamburgerModal.jsx
  client/components/PocketMoney/PocketMoneyModal.jsx
  client/components/Transaction/TransactionTypeModal.jsx
  client/hooks/use-date-picker.js
  client/pages/AccountBook.jsx
  client/pages/ManagingPocketMoney.jsx
  client/pages/SelectAccount.jsx
  client/recoil/accountBook.js
  client/recoil/pocketMoney.js
  client/recoil/user.js
  client/services/apis/accountBookAPI.js
  client/services/apis/automaticPaymentAPI.js
  client/services/apis/familyAPI.js
  client/services/apis/transactionHistoryAPI.js
  client/services/apis/userAPI.js
  client/test/dummyData/managingPocketMoney.js
  client/test/dummyData/user.js
  client/utils/const/CalendarConstant.js
  client/utils/const/api.js
Labels: enhancement
